### ISSUE TITLE
Rev0 Development Issue tracker 

### ISSUE THREAD

**Issue by marlon4dashen** [marlon4dashen/Hairesthetics#50]
**Description**
Listing things unfinished before rev0 for each feature.
\* means not necessary but good to have for rev0.

**Comment by marlon4dashen** [comment]
HairColor Module:

- [x] Color Pallete (UI)
- [x] Disconnect the socket after closing the camera (UI)
- [x] Camera controls (start, stop, etc) (UI)
- [x] Upload Image (UI)
- [x] Video endpoint param change (backend)
- [x] Endpoint for clearing processing buffer (backend)
- [x] Endpoint for processing a single image (backend)
- [ ] Alpha value slider* (UI & backend)
- [ ] Download an image or a snapshot of the live video* (UI & backend)
- [ ] Potentially improve model performance* (backend)
- [ ] Color switch delay (have to press twice to see the hair color change)* (UI & backend)

**Comment by marlon4dashen** [comment]
Salon Recommendation:
- [ ] Map flicker fix* (UI)
- [ ] Indicators when fetching results from the server (UI)
- [x] Search bar UI (UI)
- [ ] Search autocomplete latency issue* (UI)
- [x] Salon cards UI (UI)
- [ ] Google maps skin* (UI)
- [x] Bayesian average algorithm for ranking salons (backend)
- [ ] Find appropriate confidence level for the Bayesian algorithm* (backend)

**Comment by marlon4dashen** [comment]
HairStyle Module:

- [x] Working on UI
- [x] Hairstyle picker (UI)
- [x] Preload hairstyle (backend?)
- [x] Support closing page & Reload (UI)
- [x] Change color of hairstyle model* (UI & backend)
- [x] More & better hairstyle* (UI & backend)

**Comment by charlottechengg** [comment]
Documentation:
- [x]  Presentation deck
- [x]  Update documentation to match implementation and requirement change

**Comment by charlottechengg** [comment]
Home Module:
- [x] UI
- [x] logo
- [ ] font
